name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "RSpec @ Ruby ${{ matrix.ruby }}, Rails ${{ matrix.gemfile }}"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.3"
          - "head"
        gemfile:
          - gemfiles/rails_6_1.gemfile
          - gemfiles/rails_7_1.gemfile
          - gemfiles/rails_7_2.gemfile
        exclude:
            - ruby: "3.3"
              gemfile: gemfiles/rails_6_1.gemfile
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rspec
      run: bundle exec rake test

  linters:
    name: "Rubocop @ Ruby ${{ matrix.ruby }}, Rails ${{ matrix.gemfile }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "head"
        gemfile:
          - gemfiles/rails_7_2.gemfile
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop
